; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino
lib_deps = 
	gitlab-airbornemint/Protothreads@^1.4.0-arduino.beta.1
	featherfly/SoftwareSerial@^1.0
	arduino-libraries/Servo@^1.3.0
	huskylens/HuskyLens@^1.0.0
	seeed-studio/Grove - Digital Light Sensor@^2.0.0
	sparkfun/SparkFun TB6612FNG Motor Driver Library@^1.0.0
