/*
touch.h, created by Alex
Header file for "Touch.ino" in the R2D2_CAI Repository (git).
Setup code for declarations
Including bit flags & bit masks to use
*/

#ifndef TOUCH_AND_KICK
#define TOUCH_AND_KICK

#define V1          2 // changed from D4 to D2 (12-20-2025)
#define V2          A0
#define V_wiper     A1
#define V_ref_neg   5
#define V_LOW       7

typedef enum READ_STATE {
  RS_INIT = 0,
  RS_ADC,
  RS_WAIT
} eReadState_t;

typedef enum DISP_STATE {
  DS_INIT = 0,
  DS_CHECK,
  DS_PRINT,
  DS_PRESENT,
  DS_ABSENT,
  DS_WAIT
} eDispState_t;

/*
Section C of ipc_comms control variable: maps as follows (least significant bit right to left)
Written in hexadecimal: starts with "0x" instead of "0b"

[0]
[1]
[2] = MASK_IPC_Brain_Read_Confirmation          Confirmation of received event by Brain Brain to Touch
[3] = MASK_IPC_Touch_To_Brain                   Event generated by task to Brain Brain

[0]
[1]
[2] = MASK_IPC_Touch_Read_Confirmation          Confirmation of received event by Touch to Brain Brain
[3] = MASK_IPC_Brain_To_Touch                   Events generated by Brain Brain to this task

*/

#define MASK_IPC_Brain_Read_Confirmation   0x00040000 // same as 0b 0000 0000 0000 0100 0000 0000 0000 0000 - Same as Touch confirming that it read from Brain
#define MASK_IPC_Touch_To_Brain            0x00080000 // same as 0b 0000 0000 0000 1000 0000 0000 0000 0000

#define MASK_IPC_Touch_Read_Confirmation   0x00400000 // same as 0b 0000 0000 0100 0000 0000 0000 0000 0000 - Same as Brain confirming that it read from Touch
#define MASK_IPC_Brain_To_Touch            0x00800000 // same as 0b 0000 0000 1000 0000 0000 0000 0000 0000

// static int threadADCRead(struct pt* pos) __attribute__((optimize("-O0")));
// static int threadDisplay(struct pt* disp) __attribute__((optimize("-O0")));
// static int threadKick(struct pt* sol) __attribute__((optimize("-O0")));
// static int threadMain(struct pt* brain) __attribute__((optimize("-O0")));
/*
Example Use Case:
Touch task uses MASK_IPC_Touch_To_Brain (as a value) to indicate data is sent & available for Brain to read
Brain uses this as a mask instead of a value

boolean Check_Available_Brain_Event () {
  if (ipc_comms & MASK_IPC_Brain_To_Touch) {
    return true;
  }
  return false
}

void Post_Touch_Event_to_Brain () {
  ipc_comms |= MASK_IPC_Touch_Brain
}

*/


#endif