/*
Section C of ipc_comms control variable: maps as follows (least significant bit right to left)
Written in hexadecimal: starts with "0x" instead of "0b"

[0]
[1]
[2] = MASK_IPC_Logic_Read_Confirmation          Confirmation of received event by Brain Logic to Touch
[3] = MASK_IPC_Touch_To_Logic                   Event generated by task to Brain Logic

[0]
[1]
[2] = MASK_IPC_Touch_Read_Confirmation          Confirmation of received event by Touch to Brain Logic
[3] = MASK_IPC_Logic_To_Touch                   Events generated by Brain Logic to this task

*/

#define MASK_IPC_Logic_Read_Confirmation   0x00040000 // same as 0b 0000 0000 0000 0100 0000 0000 0000 0000 - Same as Touch confirming that it read from Logic
#define MASK_IPC_Touch_To_Logic            0x00080000 // same as 0b 0000 0000 0000 1000 0000 0000 0000 0000

#define MASK_IPC_Touch_Read_Confirmation   0x00400000 // same as 0b 0000 0000 0100 0000 0000 0000 0000 0000 - Same as Logic confirming that it read from Touch
#define MASK_IPC_Logic_To_Touch            0x00800000 // same as 0b 0000 0000 1000 0000 0000 0000 0000 0000

/*
Example Use Case:
Touch task uses MASK_IPC_Touch_To_Logic (as a value) to indicate data is sent & available for Logic to read
Logic uses this as a mask instead of a value

boolean Check_Available_Logic_Event () {
  if (ipc_comms & MASK_IPC_Logic_To_Touch) {
    return true;
  }
  return false
}

void Post_Touch_Event_to_Logic () {
  ipc_comms |= MASK_IPC_Touch_To_Logic
}

*/